[ups]
    driver = dummy-ups
    port = /etc/nut/dummy-ups.dev
    desc = "GPIO AC monitor (primary alias)"

[ups1]
    driver = dummy-ups
    port = /etc/nut/dummy-ups.dev
    desc = "GPIO AC monitor (TeraStation alias)"
